globalThis.__phase5aErrors=[];addEventListener('error',event=>globalThis.__phase5aErrors.push(event.message||'resource error'));addEventListener('unhandledrejection',event=>globalThis.__phase5aErrors.push(String(event.reason)));
const A='../../production_artifacts/05_asset_pilot/exports/';
const views={
home:`<section class="hero"><div class="hero-copy"><p class="eyebrow">Raw ingredient · precise measure · joyful make</p><h1>Make room for measured joy.</h1><p>Discover baking ingredients and supplies through exact packs, useful facts and recipe-led planning.</p><div class="actions"><a class="button" href="?view=department">Shop ingredients</a><a class="button alt" href="?view=recipe">Explore recipe</a></div></div><figure><picture><source media="(max-width: 760px)" srcset="${A}asset_pf5a_home_cocoa_mobile_819x1024_v1.webp"><img src="${A}asset_pf5a_home_cocoa_desktop_1536x1024_v1.webp" alt=""></picture></figure></section>`,
department:`<section class="page"><p class="eyebrow">Department 01 · Ingredients</p><h1>Measured matter.</h1><div class="atlas"><img src="${A}asset_pf5a_department_cocoa_1536x1024_v1.webp" alt="Measured cocoa powder forms with a scoop, rule and whisk."><div class="measure-note"><h2>From form to pack</h2><p>Compare ingredient form and explicit pack weight before choosing. Unknown facts stay visible.</p><a href="?view=plp">Browse dry ingredients</a></div></div></section>`,
plp:`<section class="page"><p class="eyebrow">Dry ingredients · 1 parent family</p><h1>Choose the measure.</h1><div class="grid">${[['250g','250 g','ML-BCP-250'],['500g','500 g','ML-BCP-500'],['1kg','1 kg','ML-BCP-1000']].map(([id,w,sku])=>`<article class="card"><img src="${A}asset_pf5a_plp_${id}_640_v1.webp" alt="Measureloom Baking cocoa powder, ${w} prototype pouch."><p class="eyebrow">Measureloom</p><h2>Baking cocoa powder</h2><p class="pack">${w} · ${sku}</p><a class="button" href="?view=pdp&pack=${id}">View pack</a></article>`).join('')}</div><div class="thumbtest"><figure><img class="t160" src="${A}asset_pf5a_plp_500g_640_v1.webp" alt=""><figcaption>160 px test</figcaption></figure><figure><img class="t96" src="${A}asset_pf5a_plp_500g_320_v1.webp" alt=""><figcaption>96 px test</figcaption></figure></div></section>`,
pdp:`<section class="page pdp"><div class="media"><img id="pack-img" src="${A}asset_pf5a_pack_500g_front_1200_v1.webp" alt="Measureloom Baking cocoa powder, 500 g prototype pouch."></div><div><p class="eyebrow">Measureloom · Pantryform pilot brand</p><h1>Baking cocoa powder</h1><p>Form: Powder</p><div class="variants" aria-label="Pack weight">${[['250g','250 g'],['500g','500 g'],['1kg','1 kg']].map(([id,w])=>`<button data-pack="${id}" aria-pressed="${id==='500g'}">${w}</button>`).join('')}</div><p id="selection" role="status">500 g selected · SKU ML-BCP-500</p><dl class="facts"><dt>Ingredients</dt><dd>Information not provided</dd><dt>Allergens</dt><dd>Information not provided</dd><dt>Storage</dt><dd>Information not provided</dd></dl><button>Add to demo cart</button><p class="muted">Portfolio prototype. No real availability, payment or order.</p></div></section>`,
recipe:`<section class="page"><p class="eyebrow">Original demo recipe · illustrative image</p><h1>Cocoa Celebration Cake</h1><div class="recipe-grid"><img src="${A}asset_pf5a_recipe_cocoa_cake_1536x1024_v1.webp" alt="Cocoa layer cake beside measured cocoa powder and a whisk."><div><h2>From inspiration to reviewed packs</h2><p>This editorial image is not a guaranteed result. Recipe quantities and culinary validation are outside this bounded pilot.</p><a class="button" href="?view=bridge">Review related supply</a></div></div></section>`,
bridge:`<section class="page"><p class="eyebrow">Recipe-to-supplies bridge</p><h1>One relationship, made explicit.</h1><img src="${A}asset_pf5a_recipe_cocoa_process_1200x900_v1.webp" alt="Measured cocoa powder on parchment beside a scoop." style="width:100%;max-height:430px;object-fit:cover"><div class="bridge"><div class="bridge-row"><img src="${A}asset_pf5a_plp_500g_320_v1.webp" alt=""><div><strong>Baking cocoa powder</strong><br>500 g · ML-BCP-500<br><span class="muted">Relationship only; recipe quantity not provided.</span></div><a class="button" href="?view=pdp">Review pack</a></div></div></section>`,
failure:`<section class="page"><p class="eyebrow">Image-failure contract</p><h1>Facts do not disappear.</h1><div class="fallback"><img src="${A}asset_pf5a_product_fallback_640_v1.webp" alt=""><h2>Measureloom Baking cocoa powder</h2><p>500 g · ML-BCP-500 · Form: Powder</p><p>Ingredients, allergens and storage: Information not provided.</p><a class="button" href="?view=pdp">View product facts</a></div></section>`};
const params=new URLSearchParams(location.search),view=params.get('view')||'home';if(params.get('text')==='200')document.documentElement.classList.add('text-200');if(params.get('images')==='off')document.documentElement.classList.add('images-off');document.querySelector('#main').innerHTML=views[view]||views.home;
const data={'250g':['250 g','ML-BCP-250'],'500g':['500 g','ML-BCP-500'],'1kg':['1 kg','ML-BCP-1000']};
document.querySelectorAll('[data-pack]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-pack]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');const id=b.dataset.pack,[w,sku]=data[id],img=document.querySelector('#pack-img');img.src=`${A}asset_pf5a_pack_${id}_front_1200_v1.webp`;img.alt=`Measureloom Baking cocoa powder, ${w} prototype pouch.`;document.querySelector('#selection').textContent=`${w} selected · SKU ${sku}`;}));
