// Source-of-truth data table for the R2B1 real-catalog migration.
// Every fact here traces to design_review/recovery_r1/catalog/Product_Provenance_Register.md.
// Prices are demo fixtures (site-wide disclosure); pack sizes are the register's verified sizes.
// One replacement was made per R2B1 Section 2: the single brand-unconfirmed R1 item
// ("Round Silver Cake Boards", brand unclear) is replaced with "PME Cake Drum Board" —
// PME's brand reality is already established elsewhere in the register (PME Supatube, PME
// Edible Sugar Pearls), and PME genuinely sells cake drum boards as part of its sugarcraft line.

export const DEPARTMENTS = {
  chocolate: "dept_chocolate",
  ingredients: "dept_ingredients",
  colours_flavours: "dept_colours_flavours",
  fillings_fondant: "dept_fillings_fondant",
  decorating: "dept_decorating",
  bakeware_tools: "dept_bakeware_tools",
  packaging: "dept_packaging",
};

// id, slug, brand, brand_id, department, category_id, subcategory_id, product_family,
// title, subcategory (human), packLabel, pack kind/value/unit/canonical, priceInr,
// productType, imageSlug (matches public/real-products or public/real-products-v2 file base name; null = not yet sourced)
export const PRODUCTS = [
  // Department 1: Chocolates & Cocoa (7)
  {
    id: "prod_real_callebaut_811",
    slug: "callebaut-811-dark-chocolate-callets",
    brand: "Callebaut",
    brandId: "brand_callebaut",
    dept: DEPARTMENTS.chocolate,
    cat: "cat_cocoa",
    subcat: "subcat_dark_couverture",
    family: "chocolate",
    title: "811 Dark Chocolate Callets",
    subcategoryLabel: "Dark couverture chocolate callets",
    productType: "ingredient",
    variants: [
      { sku: "CLB-811-1000", pack: { kind: "mass", value: 1, unit: "kg", canonicalValue: 1000, canonicalUnit: "g", label: "1 kg" }, priceInr: 2200, availability: "available" },
      { sku: "CLB-811-0400", pack: { kind: "mass", value: 400, unit: "g", canonicalValue: 400, canonicalUnit: "g", label: "400 g" }, priceInr: 950, availability: "available" },
    ],
    imageSlug: "callebaut-811-callets",
    imageSourceUrl: "https://www.callebaut.com/en/products/callebaut/darkchocolaterecipe811/811-2B-U73",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Callebaut 811 is a Belgian dark couverture chocolate sold in India in callet (disc) form, produced by Callebaut and commonly used by professional and home bakers for melting, molding and glazing.",
  },
  {
    id: "prod_real_morde_dark_slab",
    slug: "morde-dark-compound-chocolate-slab",
    brand: "Morde",
    brandId: "brand_morde",
    dept: DEPARTMENTS.chocolate,
    cat: "cat_baking_chocolate",
    subcat: "subcat_compound",
    family: "chocolate",
    title: "Dark Compound Chocolate Slab",
    subcategoryLabel: "Dark compound chocolate slab",
    productType: "ingredient",
    variants: [{ sku: "MRD-DCS-0500", pack: { kind: "mass", value: 500, unit: "g", canonicalValue: 500, canonicalUnit: "g", label: "500 g" }, priceInr: 250, availability: "available" }],
    imageSlug: "morde-dark-compound-slab",
    imageSourceUrl: "https://www.amazon.in/Morde-Dark-Compound-Slab-400/dp/B01IET7SUS",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Morde Dark Compound is a cocoa-solids-and-sugar-based compound chocolate slab manufactured by Morde, an Indian bakery-ingredients company, positioned as a lower-cost alternative to couverture chocolate.",
  },
  {
    id: "prod_real_van_houten_cocoa",
    slug: "van-houten-cocoa-powder",
    brand: "Van Houten",
    brandId: "brand_van_houten",
    dept: DEPARTMENTS.chocolate,
    cat: "cat_cocoa",
    subcat: "subcat_cocoa_powder",
    family: "cocoa",
    title: "Cocoa Powder (Medium Brown 10/12)",
    subcategoryLabel: "Alkalised (Dutch-processed) cocoa powder",
    productType: "ingredient",
    variants: [{ sku: "VNH-COC-1000", pack: { kind: "mass", value: 1, unit: "kg", canonicalValue: 1000, canonicalUnit: "g", label: "1 kg" }, priceInr: 650, availability: "available" }],
    imageSlug: "van-houten-cocoa-powder",
    imageSourceUrl: "https://www.hyperpure.com/in/vanhouten-by-barry-callebaut-cocoa-powder-1-kg",
    imageSourceType: "authorized_distributor",
    confidence: "verified",
    description: "Van Houten Cocoa Powder, a Dutch-processed cocoa brand now owned by Barry Callebaut, is sold in India in medium-brown grade for baking and beverage use.",
  },
  {
    id: "prod_real_amul_dark_compound_bar",
    slug: "amul-dark-compound-chocolate-bar",
    brand: "Amul",
    brandId: "brand_amul",
    dept: DEPARTMENTS.chocolate,
    cat: "cat_baking_chocolate",
    subcat: "subcat_compound",
    family: "chocolate",
    title: "Dark Compound Chocolate Bar (DCO-18)",
    subcategoryLabel: "Dark compound chocolate bar",
    productType: "ingredient",
    variants: [{ sku: "AML-DCO-0500", pack: { kind: "mass", value: 500, unit: "g", canonicalValue: 500, canonicalUnit: "g", label: "500 g" }, priceInr: 230, availability: "available" }],
    imageSlug: "amul-dark-compound-bar",
    imageSourceUrl: "https://prithvienterprises.co.in/products/amul-compound-dark-chocolate-bar-dco-18-500-g",
    imageSourceType: "authorized_distributor",
    confidence: "verified",
    description: "Amul's Dark Compound Chocolate Bar (DCO-18) is a cooking/baking compound chocolate produced by Amul and sold in a 500g bar format for melting and coating.",
  },
  {
    id: "prod_real_morde_compound_chips",
    slug: "morde-dark-compound-chocolate-chips",
    brand: "Morde",
    brandId: "brand_morde",
    dept: DEPARTMENTS.chocolate,
    cat: "cat_chips_inclusions",
    subcat: "subcat_chips",
    family: "chocolate_inclusion",
    title: "Dark Compound Chocolate Chips",
    subcategoryLabel: "Compound chocolate chips",
    productType: "ingredient",
    variants: [{ sku: "MRD-CHP-0500", pack: { kind: "mass", value: 500, unit: "g", canonicalValue: 500, canonicalUnit: "g", label: "500 g" }, priceInr: 220, availability: "available" }],
    imageSlug: "morde-compound-chips",
    imageSourceUrl: "https://www.bigbasket.com/pd/40119334/morde-chips-dark-compound-horeca-500-g/",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Morde Dark Compound Chocolate Chips are small-format compound chocolate pieces made by Morde for baking, garnishing and folding into batters.",
  },
  {
    id: "prod_real_weikfield_cocoa",
    slug: "weikfield-cocoa-powder",
    brand: "Weikfield",
    brandId: "brand_weikfield",
    dept: DEPARTMENTS.chocolate,
    cat: "cat_cocoa",
    subcat: "subcat_cocoa_powder",
    family: "cocoa",
    title: "Cocoa Powder",
    subcategoryLabel: "Unsweetened cocoa powder",
    productType: "ingredient",
    variants: [{ sku: "WKF-COC-0150", pack: { kind: "mass", value: 150, unit: "g", canonicalValue: 150, canonicalUnit: "g", label: "150 g" }, priceInr: 110, availability: "available" }],
    imageSlug: "weikfield-cocoa-powder",
    imageSourceUrl: "https://www.amazon.in/Weikfield-Cocoa-Powder-150g/dp/B075T65RM8",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Weikfield Cocoa Powder is an unsweetened cocoa powder made by Weikfield Foods Pvt. Ltd., widely distributed across Indian grocery and quick-commerce platforms.",
  },
  {
    id: "prod_real_hersheys_cocoa",
    slug: "hersheys-cocoa-powder",
    brand: "Hershey's",
    brandId: "brand_hersheys",
    dept: DEPARTMENTS.chocolate,
    cat: "cat_cocoa",
    subcat: "subcat_cocoa_powder",
    family: "cocoa",
    title: "Cocoa Powder (Natural Unsweetened)",
    subcategoryLabel: "Natural unsweetened cocoa powder",
    productType: "ingredient",
    variants: [{ sku: "HRS-COC-0225", pack: { kind: "mass", value: 225, unit: "g", canonicalValue: 225, canonicalUnit: "g", label: "225 g" }, priceInr: 399, availability: "available" }],
    imageSlug: "hersheys-cocoa-powder",
    imageSourceUrl: "https://www.hersheyland.in/products/hersheys-cocoa-natural-unsweetened-225-g.html",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Hershey's Cocoa Powder is a natural, unsweetened cocoa powder sold in India through Hershey's own India storefront and major online grocery retailers.",
  },

  // Department 2: Baking Essentials (7)
  {
    id: "prod_real_pillsbury_maida",
    slug: "pillsbury-maida",
    brand: "Pillsbury",
    brandId: "brand_pillsbury",
    dept: DEPARTMENTS.ingredients,
    cat: "cat_flours_mixes",
    subcat: "subcat_flour",
    family: "ingredient_dry",
    title: "Maida (All Purpose Flour)",
    subcategoryLabel: "Refined wheat flour (maida)",
    productType: "ingredient",
    variants: [{ sku: "PLB-MDA-1000", pack: { kind: "mass", value: 1, unit: "kg", canonicalValue: 1000, canonicalUnit: "g", label: "1 kg" }, priceInr: 65, availability: "available" }],
    imageSlug: "pillsbury-maida",
    imageSourceUrl: "https://blinkit.com/prn/pillsbury-maida/prid/598840",
    imageSourceType: "marketplace",
    confidence: "partially_verified",
    description: "Pillsbury Maida is a refined all-purpose wheat flour sold under the Pillsbury brand through Indian quick-commerce retail.",
  },
  {
    id: "prod_real_weikfield_baking_powder",
    slug: "weikfield-double-action-baking-powder",
    brand: "Weikfield",
    brandId: "brand_weikfield",
    dept: DEPARTMENTS.ingredients,
    cat: "cat_leavening_essentials",
    subcat: "subcat_leavener",
    family: "ingredient_dry",
    title: "Double Action Baking Powder",
    subcategoryLabel: "Baking powder",
    productType: "ingredient",
    variants: [{ sku: "WKF-BPW-0100", pack: { kind: "mass", value: 100, unit: "g", canonicalValue: 100, canonicalUnit: "g", label: "100 g" }, priceInr: 40, availability: "available" }],
    imageSlug: "weikfield-baking-powder",
    imageSourceUrl: "https://www.amazon.in/Weikfield-Baking-Powder-100g/dp/B004KFHIBK",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Weikfield Double Action Baking Powder is a sodium-bicarbonate-based leavening agent manufactured by Weikfield Foods Pvt. Ltd. and sold in a reusable poly jar.",
  },
  {
    id: "prod_real_weikfield_corn_flour",
    slug: "weikfield-corn-flour",
    brand: "Weikfield",
    brandId: "brand_weikfield",
    dept: DEPARTMENTS.ingredients,
    cat: "cat_flours_mixes",
    subcat: "subcat_corn_starch",
    family: "ingredient_dry",
    title: "Corn Flour",
    subcategoryLabel: "Corn starch (corn flour)",
    productType: "ingredient",
    variants: [{ sku: "WKF-CRF-0500", pack: { kind: "mass", value: 500, unit: "g", canonicalValue: 500, canonicalUnit: "g", label: "500 g" }, priceInr: 90, availability: "available" }],
    imageSlug: "weikfield-corn-flour",
    imageSourceUrl: "https://www.flipkart.com/weikfield-cornflour-500gm/p/itmc1a7f0894ca32",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Weikfield Corn Flour is a corn-starch product, one of Weikfield's original two products since the company's 1956 founding in Pune, used for thickening and baking.",
  },
  {
    id: "prod_real_urban_platter_baking_soda",
    slug: "urban-platter-baking-soda",
    brand: "Urban Platter",
    brandId: "brand_urban_platter",
    dept: DEPARTMENTS.ingredients,
    cat: "cat_leavening_essentials",
    subcat: "subcat_baking_soda",
    family: "ingredient_dry",
    title: "Baking Soda",
    subcategoryLabel: "Food-grade sodium bicarbonate",
    productType: "ingredient",
    variants: [{ sku: "URP-SOD-0250", pack: { kind: "mass", value: 250, unit: "g", canonicalValue: 250, canonicalUnit: "g", label: "250 g" }, priceInr: 120, availability: "available" }],
    imageSlug: "urban-platter-baking-soda",
    imageSourceUrl: "https://urbanplatter.com/products/urban-platter-baking-soda-food-grade-sodium-bicarbonate-perfect-for-baking-cooking-cleaning-triple-refined",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Urban Platter Baking Soda is a triple-refined, food-grade sodium bicarbonate sold by Urban Platter through its own site and major Indian marketplaces.",
  },
  {
    id: "prod_real_eagle_icing_sugar",
    slug: "eagle-icing-sugar",
    brand: "Eagle",
    brandId: "brand_eagle",
    dept: DEPARTMENTS.ingredients,
    cat: "cat_sugars_sweeteners",
    subcat: "subcat_sugar",
    family: "ingredient_dry",
    title: "Icing Sugar",
    subcategoryLabel: "Icing / confectioner's sugar",
    productType: "ingredient",
    variants: [{ sku: "EGL-ICS-0200", pack: { kind: "mass", value: 200, unit: "g", canonicalValue: 200, canonicalUnit: "g", label: "200 g" }, priceInr: 55, availability: "available" }],
    imageSlug: "eagle-icing-sugar",
    imageSourceUrl: "https://www.bigbasket.com/pd/40009312/eagle-icing-sugar-200-g-pouch/",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Eagle Icing Sugar is a finely ground powdered sugar sold under the Eagle brand of Indian branded foods through BigBasket and other grocery retailers.",
  },
  {
    id: "prod_real_weikfield_custard_powder",
    slug: "weikfield-vanilla-custard-powder",
    brand: "Weikfield",
    brandId: "brand_weikfield",
    dept: DEPARTMENTS.ingredients,
    cat: "cat_sugars_sweeteners",
    subcat: "subcat_custard_powder",
    family: "ingredient_dry",
    title: "Vanilla Custard Powder",
    subcategoryLabel: "Custard powder",
    productType: "ingredient",
    variants: [{ sku: "WKF-CST-0100", pack: { kind: "mass", value: 100, unit: "g", canonicalValue: 100, canonicalUnit: "g", label: "100 g" }, priceInr: 50, availability: "available" }],
    imageSlug: "weikfield-vanilla-custard-powder",
    imageSourceUrl: "https://www.amazon.in/Weikfield-ET-09-Custard-Powder-Vanilla/dp/B00LK2L19Q",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Weikfield Vanilla Custard Powder is an egg-free, vanilla-flavoured custard mix manufactured by Weikfield Foods Pvt. Ltd. for fillings, trifles and desserts.",
  },
  {
    id: "prod_real_ccds_baking_powder",
    slug: "ccds-baking-powder",
    brand: "CCDS",
    brandId: "brand_ccds",
    dept: DEPARTMENTS.ingredients,
    cat: "cat_leavening_essentials",
    subcat: "subcat_leavener",
    family: "ingredient_dry",
    title: "Baking Powder",
    subcategoryLabel: "Baking powder",
    productType: "ingredient",
    variants: [{ sku: "CCD-BPW-0001", pack: { kind: "count", value: 1, unit: "pack", canonicalValue: 1, canonicalUnit: "pack", label: "1 pack (size not stated)" }, priceInr: 45, availability: "available" }],
    imageSlug: "ccds-baking-powder",
    imageSourceUrl: "https://www.ccdsshop.com/baking-powder",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "CCDS Baking Powder is sold as a house/store-branded product through CCDS's own online shop, one of India's larger cake-decorating and baking-supply store chains.",
  },

  // Department 3: Colours, Flavours & Essences (7)
  {
    id: "prod_real_magic_colours_gel",
    slug: "magic-colours-spectral-gel-colours",
    brand: "Magic Colours",
    brandId: "brand_magic_colours",
    dept: DEPARTMENTS.colours_flavours,
    cat: "cat_food_colours",
    subcat: "subcat_gel",
    family: "colour",
    title: "Spectral Gel Colour — Red",
    subcategoryLabel: "Concentrated gel food colour",
    productType: "ingredient",
    variants: [{ sku: "MGC-GEL-0025", pack: { kind: "mass", value: 25, unit: "g", canonicalValue: 25, canonicalUnit: "g", label: "25 g" }, priceInr: 180, availability: "available" }],
    imageSlug: "magic-colours-gel-red",
    imageSourceUrl: "https://magiccolours.co.in/collections/spectral-gel-colours",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Magic Colours Spectral Gel Colours are concentrated, highly pigmented gel food colours manufactured in India under license by Motek Sugarcrafts.",
  },
  {
    id: "prod_real_magic_colours_genie_tube",
    slug: "magic-colours-spectral-genie-gel-tube",
    brand: "Magic Colours",
    brandId: "brand_magic_colours",
    dept: DEPARTMENTS.colours_flavours,
    cat: "cat_food_colours",
    subcat: "subcat_gel",
    family: "colour",
    title: "Spectral Genie Gel Tube Colours",
    subcategoryLabel: "Gel food colour (tube format)",
    productType: "ingredient",
    variants: [{ sku: "MGC-GNT-0025", pack: { kind: "mass", value: 25, unit: "g", canonicalValue: 25, canonicalUnit: "g", label: "25 g" }, priceInr: 190, availability: "available" }],
    imageSlug: "magic-colours-genie-gel-tube",
    imageSourceUrl: "https://magiccolours.co.in/products/spectral-genie-gel-tube-colours",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "The Spectral Genie Gel is a tube-format version of Magic Colours' gel food colour line, an alternative dispensing format to the brand's bottled gels.",
  },
  {
    id: "prod_real_colourmist_gel_paste",
    slug: "colourmist-soft-gel-paste-set",
    brand: "Colourmist",
    brandId: "brand_colourmist",
    dept: DEPARTMENTS.colours_flavours,
    cat: "cat_food_colours",
    subcat: "subcat_gel_paste",
    family: "colour",
    title: "Soft Gel Paste Food Colours (10-Pack)",
    subcategoryLabel: "Gel paste food colour set",
    productType: "ingredient",
    variants: [{ sku: "CLM-GPS-0010", pack: { kind: "count", value: 10, unit: "bottles", canonicalValue: 10, canonicalUnit: "bottles", label: "10 x 10 g set" }, priceInr: 350, availability: "available" }],
    imageSlug: "colourmist-gel-paste-set",
    imageSourceUrl: "https://www.amazon.in/Colourmist-Vibrant-Assorted-Colours-Violet/dp/B09NM6Y3DP",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Colourmist Soft Gel Paste is a concentrated, highly pigmented food-colour line manufactured by Bakersville India Pvt. Ltd. and sold across major Indian marketplaces.",
  },
  {
    id: "prod_real_puramate_liquid_colour",
    slug: "puramate-liquid-food-colour",
    brand: "Puramate",
    brandId: "brand_puramate",
    dept: DEPARTMENTS.colours_flavours,
    cat: "cat_food_colours",
    subcat: "subcat_liquid_colour",
    family: "colour",
    title: "Liquid Food Colour",
    subcategoryLabel: "Liquid food colour",
    productType: "ingredient",
    variants: [{ sku: "PUR-LFC-0001", pack: { kind: "count", value: 1, unit: "bottle", canonicalValue: 1, canonicalUnit: "bottle", label: "1 bottle (volume not stated)" }, priceInr: 40, availability: "available" }],
    imageSlug: "puramate-liquid-food-colour",
    imageSourceUrl: "https://puramate.in/product-category/essence-and-colors/liquid-food-colors/",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Puramate Liquid Food Colour is part of Puramate's essence-and-colours product line, sold through the brand's own site and Indian quick-commerce platforms.",
  },
  {
    id: "prod_real_puramate_essence_set",
    slug: "puramate-culinary-essence-set",
    brand: "Puramate",
    brandId: "brand_puramate",
    dept: DEPARTMENTS.colours_flavours,
    cat: "cat_flavours_extracts",
    subcat: "subcat_essence",
    family: "flavour",
    title: "Culinary Essence Assorted Pack",
    subcategoryLabel: "Flavour essence",
    productType: "ingredient",
    variants: [{ sku: "PUR-ESS-0010", pack: { kind: "count", value: 10, unit: "bottles", canonicalValue: 10, canonicalUnit: "bottles", label: "10 x 30 ml set" }, priceInr: 320, availability: "available" }],
    imageSlug: "puramate-culinary-essence-set",
    imageSourceUrl: "https://www.amazon.in/Puramate-Pineapple-Butterscotch-Strawberry-Chocolate/dp/B08PPKD7BV",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Puramate Culinary Essence Assorted is a 10-flavour set of liquid flavour essences sold by Puramate, an Indian FMCG brand founded in 2019.",
  },
  {
    id: "prod_real_urban_platter_vanilla",
    slug: "urban-platter-premium-vanilla-extract",
    brand: "Urban Platter",
    brandId: "brand_urban_platter",
    dept: DEPARTMENTS.colours_flavours,
    cat: "cat_flavours_extracts",
    subcat: "subcat_vanilla_extract",
    family: "flavour",
    title: "Premium Vanilla Extract",
    subcategoryLabel: "Vanilla extract (alcohol-free)",
    productType: "ingredient",
    variants: [
      { sku: "URP-VAN-0150", pack: { kind: "volume", value: 150, unit: "ml", canonicalValue: 150, canonicalUnit: "ml", label: "150 ml" }, priceInr: 400, availability: "available" },
      { sku: "URP-VAN-0100", pack: { kind: "volume", value: 100, unit: "ml", canonicalValue: 100, canonicalUnit: "ml", label: "100 ml" }, priceInr: 280, availability: "available" },
    ],
    imageSlug: "urban-platter-vanilla-extract",
    imageSourceUrl: "https://urbanplatter.com/products/urban-platter-premium-vanilla-extract-100ml-made-with-real-indian-vanilla-perfect-for-baking-alcohol-free",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Urban Platter Premium Vanilla Extract is an alcohol-free vanilla extract marketed as made with real Indian vanilla, sold via the brand's own site and Indian marketplaces.",
  },
  {
    id: "prod_real_wilton_gel_icing_color",
    slug: "wilton-gel-food-coloring-icing-color",
    brand: "Wilton",
    brandId: "brand_wilton",
    dept: DEPARTMENTS.colours_flavours,
    cat: "cat_food_colours",
    subcat: "subcat_gel",
    family: "colour",
    title: "Gel Food Coloring Icing Color",
    subcategoryLabel: "Concentrated gel icing colour",
    productType: "ingredient",
    variants: [{ sku: "WLT-GIC-0001", pack: { kind: "count", value: 1, unit: "jar", canonicalValue: 1, canonicalUnit: "jar", label: "1 jar (~1 oz)" }, priceInr: 280, availability: "available" }],
    imageSlug: "wilton-gel-icing-color",
    imageSourceUrl: "https://www.flipkart.com/wilton-gel-food-coloring-icing-color-pink/p/itm771768d71ed62",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Wilton Gel Food Coloring is a concentrated gel-based icing colour line from the US bakeware and decorating brand Wilton.",
  },

  // Department 4: Fondant, Fillings & Toppings (7)
  {
    id: "prod_real_bakersville_vizyon_fondant",
    slug: "bakersville-vizyon-sugar-paste-white",
    brand: "Bakersville",
    brandId: "brand_bakersville",
    dept: DEPARTMENTS.fillings_fondant,
    cat: "cat_fondant_modelling",
    subcat: "subcat_rolled_fondant",
    family: "fondant",
    title: "Vizyon Sugar Paste — White",
    subcategoryLabel: "Ready-to-use rolled fondant",
    productType: "ingredient",
    variants: [{ sku: "BKV-VIZ-1000", pack: { kind: "mass", value: 1, unit: "kg", canonicalValue: 1000, canonicalUnit: "g", label: "1 kg" }, priceInr: 450, availability: "available" }],
    imageSlug: "bakersville-vizyon-fondant-white",
    imageSourceUrl: "https://www.indiamart.com/bakersvilleindiapvtltd-indore/sugar-paste.html",
    imageSourceType: "authorized_distributor",
    confidence: "verified",
    description: "Vizyon Sugar Paste is a ready-to-use fondant/sugar paste line supplied by Bakersville India Pvt. Ltd. for covering cakes and modelling decorations.",
  },
  {
    id: "prod_real_tropolite_whip_topping",
    slug: "tropolite-premium-whip-topping-cream",
    brand: "Tropolite",
    brandId: "brand_tropolite",
    dept: DEPARTMENTS.fillings_fondant,
    cat: "cat_fillings_glazes",
    subcat: "subcat_whip_topping",
    family: "filling",
    title: "Premium Whip Topping Cream",
    subcategoryLabel: "Non-dairy whipping cream",
    productType: "ingredient",
    variants: [{ sku: "TRP-WHP-0500", pack: { kind: "mass", value: 500, unit: "g", canonicalValue: 500, canonicalUnit: "g", label: "500 g" }, priceInr: 320, availability: "available" }],
    imageSlug: "tropolite-whip-topping",
    imageSourceUrl: "https://tropolite.com/bakery/whipping-creams/supreme-whip-topping",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Tropolite Premium Whip Topping Cream is a non-dairy whipping cream produced by Tropilite Foods for cake and pastry icing/decoration.",
  },
  {
    id: "prod_real_richs_whip_topping",
    slug: "richs-chocolate-whip-topping",
    brand: "Rich's",
    brandId: "brand_richs",
    dept: DEPARTMENTS.fillings_fondant,
    cat: "cat_fillings_glazes",
    subcat: "subcat_whip_topping",
    family: "filling",
    title: "Chocolate Whip Topping",
    subcategoryLabel: "Flavoured whip topping cream",
    productType: "ingredient",
    variants: [{ sku: "RCH-WHP-1000", pack: { kind: "mass", value: 1, unit: "kg", canonicalValue: 1000, canonicalUnit: "g", label: "1 kg" }, priceInr: 420, availability: "available" }],
    imageSlug: "richs-chocolate-whip-topping",
    imageSourceUrl: "https://www.richs.in/product/richs-chocolate-whip-topping/",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Rich's Chocolate Whip Topping is a chocolate-flavoured non-dairy whipped topping sold through Rich's India's own online store.",
  },
  {
    id: "prod_real_richs_truffle_base",
    slug: "richs-truffle-base",
    brand: "Rich's",
    brandId: "brand_richs",
    dept: DEPARTMENTS.fillings_fondant,
    cat: "cat_fillings_glazes",
    subcat: "subcat_ganache",
    family: "filling",
    title: "Truffle Base",
    subcategoryLabel: "Chocolate ganache / truffle base",
    productType: "ingredient",
    variants: [{ sku: "RCH-TRB-0001", pack: { kind: "count", value: 1, unit: "tub", canonicalValue: 1, canonicalUnit: "tub", label: "1 tub (size not stated)" }, priceInr: 550, availability: "available" }],
    imageSlug: "richs-truffle-base",
    imageSourceUrl: "https://www.richs.in/product/richs-truffle-base/",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Rich's Truffle Base is a ready-to-use chocolate ganache-style base product for fillings, glazes and truffle-style desserts.",
  },
  {
    id: "prod_real_funcakes_fondant",
    slug: "funcakes-rolled-fondant",
    brand: "FunCakes",
    brandId: "brand_funcakes",
    dept: DEPARTMENTS.fillings_fondant,
    cat: "cat_fondant_modelling",
    subcat: "subcat_rolled_fondant",
    family: "fondant",
    title: "Rolled Fondant",
    subcategoryLabel: "Rolled fondant",
    productType: "ingredient",
    variants: [{ sku: "FNC-FND-0250", pack: { kind: "mass", value: 250, unit: "g", canonicalValue: 250, canonicalUnit: "g", label: "250 g" }, priceInr: 380, availability: "available" }],
    imageSlug: "funcakes-rolled-fondant",
    imageSourceUrl: "https://www.sweetnfairy.com/en/funcakes/874-rolled-fondant-funcakes-250g-8720143514432.html",
    imageSourceType: "authorized_distributor",
    confidence: "partially_verified",
    description: "FunCakes Rolled Fondant is a European ready-to-roll fondant brand distributed to cake-decorating retailers internationally, including sellers that ship to India.",
  },
  {
    id: "prod_real_nutella_spread",
    slug: "nutella-hazelnut-spread-with-cocoa",
    brand: "Nutella (Ferrero)",
    brandId: "brand_nutella",
    dept: DEPARTMENTS.fillings_fondant,
    cat: "cat_fillings_glazes",
    subcat: "subcat_spread",
    family: "filling",
    title: "Hazelnut Spread with Cocoa",
    subcategoryLabel: "Chocolate-hazelnut spread / filling",
    productType: "ingredient",
    variants: [
      { sku: "NTL-SPR-0750", pack: { kind: "mass", value: 750, unit: "g", canonicalValue: 750, canonicalUnit: "g", label: "750 g" }, priceInr: 750, availability: "available" },
      { sku: "NTL-SPR-0200", pack: { kind: "mass", value: 200, unit: "g", canonicalValue: 200, canonicalUnit: "g", label: "200 g" }, priceInr: 250, availability: "available" },
    ],
    imageSlug: "nutella-hazelnut-spread",
    imageSourceUrl: "https://www.amazon.in/Nutella-Hazelnut-Spread-Cocoa-750g/dp/B008TMIO2M",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Nutella Hazelnut Spread with Cocoa is Ferrero's globally distributed hazelnut-cocoa spread, sold in India through major online grocery platforms.",
  },
  {
    id: "prod_real_amul_fresh_cream",
    slug: "amul-fresh-cream-25-percent",
    brand: "Amul",
    brandId: "brand_amul",
    dept: DEPARTMENTS.fillings_fondant,
    cat: "cat_fillings_glazes",
    subcat: "subcat_dairy_cream",
    family: "filling",
    title: "Fresh Cream (25% Milk Fat)",
    subcategoryLabel: "Dairy cream for whipping/filling",
    productType: "ingredient",
    variants: [{ sku: "AML-CRM-0250", pack: { kind: "volume", value: 250, unit: "ml", canonicalValue: 250, canonicalUnit: "ml", label: "250 ml" }, priceInr: 65, availability: "available" }],
    imageSlug: "amul-fresh-cream",
    imageSourceUrl: "https://www.bigbasket.com/pd/40102603/amul-fresh-cream-25-milk-fat-low-fat-250-ml/",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Amul Fresh Cream is a 25%-milk-fat dairy cream sold in tetra packs by Amul, commonly used for whipping and cake fillings.",
  },

  // Department 5: Sprinkles & Edible Decoration (7)
  {
    id: "prod_real_wilton_edible_sprinkles",
    slug: "wilton-edible-baking-sprinkles",
    brand: "Wilton",
    brandId: "brand_wilton",
    dept: DEPARTMENTS.decorating,
    cat: "cat_sprinkles_decor",
    subcat: "subcat_sprinkles",
    family: "decorating_consumable",
    title: "Edible Baking Sprinkles",
    subcategoryLabel: "Mixed sprinkles",
    productType: "consumable",
    variants: [{ sku: "WLT-SPR-0001", pack: { kind: "count", value: 1, unit: "jar", canonicalValue: 1, canonicalUnit: "jar", label: "1 jar (size not stated)" }, priceInr: 320, availability: "available" }],
    imageSlug: "wilton-edible-sprinkles",
    imageSourceUrl: "https://www.flipkart.com/wilton-edible-baking-sprinkles/p/itmehv7mzr2gaz4w",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Wilton Edible Baking Sprinkles is a cake and cupcake decoration sprinkle mix from Wilton, listed for sale to Indian customers.",
  },
  {
    id: "prod_real_wilton_rainbow_nonpareils",
    slug: "wilton-rainbow-nonpareils",
    brand: "Wilton",
    brandId: "brand_wilton",
    dept: DEPARTMENTS.decorating,
    cat: "cat_sprinkles_decor",
    subcat: "subcat_nonpareils",
    family: "decorating_consumable",
    title: "Rainbow Nonpareils",
    subcategoryLabel: "Nonpareil sprinkles",
    productType: "consumable",
    variants: [{ sku: "WLT-NPL-0001", pack: { kind: "mass", value: 7.8, unit: "oz", canonicalValue: 221, canonicalUnit: "g", label: "7.8 oz" }, priceInr: 350, availability: "available" }],
    imageSlug: "wilton-rainbow-nonpareils",
    imageSourceUrl: "https://wilton.com/rainbow-nonpareils-7-8oz/191008777/",
    imageSourceType: "manufacturer",
    confidence: "partially_verified",
    description: "Wilton Rainbow Nonpareils are small round sprinkles sold by Wilton for topping cupcakes, cookies and cakes.",
  },
  {
    id: "prod_real_bakersville_wow_confetti",
    slug: "bakersville-wow-confetti-deco-sprinkles",
    brand: "Bakersville",
    brandId: "brand_bakersville",
    dept: DEPARTMENTS.decorating,
    cat: "cat_sprinkles_decor",
    subcat: "subcat_confetti",
    family: "decorating_consumable",
    title: "Wow Confetti Deco Sprinkles",
    subcategoryLabel: "Confetti / deco sprinkles",
    productType: "consumable",
    variants: [{ sku: "BKV-WOW-0200", pack: { kind: "mass", value: 200, unit: "g", canonicalValue: 200, canonicalUnit: "g", label: "200 g" }, priceInr: 150, availability: "available" }],
    imageSlug: "bakersville-wow-confetti",
    imageSourceUrl: "https://www.bakersvilleshop.com/collections/wow-confetti-deco-sprinkles",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Wow Confetti is Bakersville's edible confetti/deco sprinkle range, sold through the brand's own storefronts for cake, cupcake and dessert decoration.",
  },
  {
    id: "prod_real_bakersville_glint_pearl_spray",
    slug: "bakersville-glint-pearl-spray",
    brand: "Bakersville",
    brandId: "brand_bakersville",
    dept: DEPARTMENTS.decorating,
    cat: "cat_sprinkles_decor",
    subcat: "subcat_pearl_spray",
    family: "decorating_consumable",
    title: "Glint Pearl Spray",
    subcategoryLabel: "Edible pearl-finish spray",
    productType: "consumable",
    variants: [{ sku: "BKV-GLT-0001", pack: { kind: "count", value: 1, unit: "can", canonicalValue: 1, canonicalUnit: "can", label: "1 can (size not stated)" }, priceInr: 380, availability: "available" }],
    imageSlug: "bakersville-glint-pearl-spray",
    imageSourceUrl: "https://bakersville.in/product-category/metaglo/pearl-spray/",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Glint Pearl Spray is an edible spray product from Bakersville's Glint range, marketed for giving cakes and desserts a pearlescent finish.",
  },
  {
    id: "prod_real_jvg_chocolate_sprinkles",
    slug: "jvg-chocolate-vermicelli-sprinkles",
    brand: "JVG",
    brandId: "brand_jvg",
    dept: DEPARTMENTS.decorating,
    cat: "cat_sprinkles_decor",
    subcat: "subcat_sprinkles",
    family: "decorating_consumable",
    title: "Chocolate Vermicelli Sprinkles",
    subcategoryLabel: "Chocolate vermicelli sprinkles",
    productType: "consumable",
    variants: [{ sku: "JVG-CHS-1000", pack: { kind: "mass", value: 1, unit: "kg", canonicalValue: 1000, canonicalUnit: "g", label: "1 kg" }, priceInr: 380, availability: "available" }],
    imageSlug: "jvg-chocolate-sprinkles",
    imageSourceUrl: "https://www.jvgtraders.com/decoration-sprinkles.html",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "JVG Chocolate Sprinkles are chocolate-flavoured decoration sprinkles manufactured by JVG Traders Private Limited for cake and ice-cream decoration.",
  },
  {
    id: "prod_real_jvg_rainbow_sprinkles",
    slug: "jvg-rainbow-sprinkles",
    brand: "JVG",
    brandId: "brand_jvg",
    dept: DEPARTMENTS.decorating,
    cat: "cat_sprinkles_decor",
    subcat: "subcat_sprinkles",
    family: "decorating_consumable",
    title: "Rainbow Sprinkles",
    subcategoryLabel: "Rainbow sprinkles",
    productType: "consumable",
    variants: [{ sku: "JVG-RBS-1000", pack: { kind: "mass", value: 1, unit: "kg", canonicalValue: 1000, canonicalUnit: "g", label: "1 kg" }, priceInr: 380, availability: "available" }],
    imageSlug: "jvg-rainbow-sprinkles",
    imageSourceUrl: "https://www.indiamart.com/jvg-traders-ltd/decoration-sprinkles.html",
    imageSourceType: "authorized_distributor",
    confidence: "verified",
    description: "JVG Rainbow Sprinkles are multi-coloured decoration sprinkles manufactured by JVG Traders Private Limited for cake and ice-cream decoration.",
  },
  {
    id: "prod_real_pme_sugar_pearls",
    slug: "pme-edible-sugar-pearls",
    brand: "PME",
    brandId: "brand_pme",
    dept: DEPARTMENTS.decorating,
    cat: "cat_sprinkles_decor",
    subcat: "subcat_sugar_pearls",
    family: "decorating_consumable",
    title: "Edible Sugar Pearls",
    subcategoryLabel: "Sugar pearl cake decorations",
    productType: "consumable",
    variants: [{ sku: "PME-PRL-0001", pack: { kind: "count", value: 1, unit: "tub", canonicalValue: 1, canonicalUnit: "tub", label: "1 tub (weight varies by colour/size)" }, priceInr: 320, availability: "available" }],
    imageSlug: "pme-sugar-pearls",
    imageSourceUrl: "https://www.amazon.com/PME-Edible-Silver-Topping-Decoration/dp/B01HMHNEPG",
    imageSourceType: "marketplace",
    confidence: "partially_verified",
    description: "PME Edible Sugar Pearls are small sugar-ball decorations, part of PME's Sugarcraft range, made in Germany for PME and sold internationally.",
  },

  // Department 6: Baking Tools & Bakeware (7)
  {
    id: "prod_real_wilton_decorating_bags",
    slug: "wilton-16-inch-disposable-decorating-bags",
    brand: "Wilton",
    brandId: "brand_wilton",
    dept: DEPARTMENTS.bakeware_tools,
    cat: "cat_piping_finishing",
    subcat: "subcat_bags",
    family: "tool",
    title: "16-Inch Disposable Decorating Bags",
    subcategoryLabel: "Disposable piping bags",
    productType: "tool",
    variants: [{ sku: "WLT-BAG-0012", pack: { kind: "count", value: 12, unit: "count", canonicalValue: 12, canonicalUnit: "count", label: "12-pack" }, priceInr: 450, availability: "available" }],
    imageSlug: "wilton-decorating-bags",
    imageSourceUrl: "https://www.amazon.in/Wilton-Disposable-16-Inch-Decorating-Bags/dp/B00175TFJ4",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "Wilton 16-Inch Disposable Decorating Bags are single-use piping bags sold by Wilton and listed for direct purchase on Amazon.in.",
  },
  {
    id: "prod_real_wilton_pan_set",
    slug: "wilton-aluminum-round-cake-pan-set",
    brand: "Wilton",
    brandId: "brand_wilton",
    dept: DEPARTMENTS.bakeware_tools,
    cat: "cat_pans_moulds",
    subcat: "subcat_round_pan",
    family: "bakeware",
    title: "Aluminum Round Cake Pan Set",
    subcategoryLabel: "Cake pans",
    productType: "tool",
    variants: [{ sku: "WLT-PAN-0004", pack: { kind: "count", value: 4, unit: "count", canonicalValue: 4, canonicalUnit: "count", label: "Set of 4 (6/8/10/12 in)" }, priceInr: 3200, availability: "available" }],
    imageSlug: "wilton-aluminum-pan-set",
    imageSourceUrl: "https://www.amazon.com/Wilton-Performance-Aluminum-Round-Medium/dp/B0000VZ2QG",
    imageSourceType: "marketplace",
    confidence: "partially_verified",
    description: "Wilton's Aluminum Bakeware Round Tiered Cake Pan Set is a four-piece anodized-aluminum pan set designed for even heat distribution.",
  },
  {
    id: "prod_real_borosil_baking_dish",
    slug: "borosil-round-baking-serving-dish",
    brand: "Borosil",
    brandId: "brand_borosil",
    dept: DEPARTMENTS.bakeware_tools,
    cat: "cat_pans_moulds",
    subcat: "subcat_bakeware_dish",
    family: "bakeware",
    title: "Round Baking & Serving Dish",
    subcategoryLabel: "Borosilicate glass bakeware",
    productType: "tool",
    variants: [{ sku: "BRS-DSH-1200", pack: { kind: "volume", value: 1.2, unit: "L", canonicalValue: 1200, canonicalUnit: "ml", label: "1.2 L" }, priceInr: 899, availability: "available" }],
    imageSlug: "borosil-baking-dish",
    imageSourceUrl: "https://myborosil.com/products/colours-blue-round-cake-dish-1-2l",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Borosil's Round Baking & Serving Dish is a borosilicate-glass bakeware item marketed by Borosil as oven-, microwave- and dishwasher-safe.",
  },
  {
    id: "prod_real_wonderchef_cake_mould",
    slug: "wonderchef-non-stick-cake-mould",
    brand: "Wonderchef",
    brandId: "brand_wonderchef",
    dept: DEPARTMENTS.bakeware_tools,
    cat: "cat_pans_moulds",
    subcat: "subcat_cake_mould",
    family: "bakeware",
    title: "Non-Stick Cake Mould",
    subcategoryLabel: "Non-stick bakeware cake mould",
    productType: "tool",
    variants: [{ sku: "WDC-MLD-0001", pack: { kind: "count", value: 1, unit: "mould", canonicalValue: 1, canonicalUnit: "mould", label: "1 mould (size varies)" }, priceInr: 650, availability: "available" }],
    imageSlug: "wonderchef-cake-mould",
    imageSourceUrl: "https://www.wonderchef.com/collections/bakeware/cake-moulds",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "Wonderchef's Cake Moulds line is a non-stick bakeware range sold directly through Wonderchef's own India ecommerce site.",
  },
  {
    id: "prod_real_pme_supatube",
    slug: "pme-supatube-piping-tip",
    brand: "PME",
    brandId: "brand_pme",
    dept: DEPARTMENTS.bakeware_tools,
    cat: "cat_piping_finishing",
    subcat: "subcat_piping_tip",
    family: "tool",
    title: "Supatube Piping Tip (Writer #1)",
    subcategoryLabel: "Seamless stainless-steel piping/writing tip",
    productType: "tool",
    variants: [{ sku: "PME-SUP-0001", pack: { kind: "count", value: 1, unit: "tip", canonicalValue: 1, canonicalUnit: "tip", label: "1 tip" }, priceInr: 280, availability: "available" }],
    imageSlug: "pme-supatube-tip",
    imageSourceUrl: "https://www.amazon.com/PME-Seamless-Stainless-SupaTube-Decorating/dp/B00EW4G98C",
    imageSourceType: "marketplace",
    confidence: "partially_verified",
    description: "The PME Supatube is a seamless stainless-steel decorating tip made in England for PME, used for fine writing and string work on cakes.",
  },
  {
    id: "prod_real_ateco_tip_set",
    slug: "ateco-55-piece-cake-decorating-tip-set",
    brand: "Ateco",
    brandId: "brand_ateco",
    dept: DEPARTMENTS.bakeware_tools,
    cat: "cat_piping_finishing",
    subcat: "subcat_tip_set",
    family: "tool",
    title: "55-Piece Cake Decorating Tip Set",
    subcategoryLabel: "Cake decorating tip set",
    productType: "tool",
    variants: [{ sku: "ATC-TIP-0055", pack: { kind: "count", value: 55, unit: "pieces", canonicalValue: 55, canonicalUnit: "pieces", label: "55-piece boxed set" }, priceInr: 2800, availability: "available" }],
    imageSlug: "ateco-tip-set",
    imageSourceUrl: "https://www.amazon.com/Ateco-Decorating-Stainless-Standard-Coupler/dp/B0000DE12F",
    imageSourceType: "marketplace",
    confidence: "partially_verified",
    description: "The Ateco 783 is a 55-piece piping tip set containing writing, star, leaf, rose, grass, basketweave and flower tips in a hinged storage box.",
  },
  {
    id: "prod_real_lukzer_decorating_kit",
    slug: "lukzer-cake-decorating-kit-with-turntable",
    brand: "Lukzer",
    brandId: "brand_lukzer",
    dept: DEPARTMENTS.bakeware_tools,
    cat: "cat_pans_moulds",
    subcat: "subcat_turntable",
    family: "tool",
    title: "Cake Decorating Kit with Turntable",
    subcategoryLabel: "Cake decorating turntable and tool kit",
    productType: "tool",
    variants: [{ sku: "LKZ-KIT-0046", pack: { kind: "count", value: 46, unit: "pieces", canonicalValue: 46, canonicalUnit: "pieces", label: "46-piece kit (approx.)" }, priceInr: 650, availability: "available" }],
    imageSlug: "lukzer-cake-decorating-kit",
    imageSourceUrl: "https://www.amazon.in/Lukzer-Turntable-Table-Baking-Tools/dp/B07G5C95TB",
    imageSourceType: "marketplace",
    confidence: "verified",
    description: "The Lukzer listing photographs a bundled cake decorating kit including a 360-degree turntable and a tool set, sold directly on Amazon.in.",
  },

  // Department 7: Cake Boards, Boxes & Packaging (6)
  {
    id: "prod_real_pme_cake_drum_board",
    slug: "pme-cake-drum-board",
    brand: "PME",
    brandId: "brand_pme",
    dept: DEPARTMENTS.packaging,
    cat: "cat_boards_bases",
    subcat: "subcat_cake_drum",
    family: "packaging",
    title: "Cake Drum Board (Round, Silver)",
    subcategoryLabel: "Silver cake drum board",
    productType: "packaging",
    variants: [{ sku: "PME-DRM-0012", pack: { kind: "count", value: 1, unit: "board", canonicalValue: 1, canonicalUnit: "board", label: "1 board (12 in round)" }, priceInr: 450, availability: "available" }],
    imageSlug: "pme-cake-drum-board",
    imageSourceUrl: "https://www.amazon.com/s?k=PME+cake+drum+board",
    imageSourceType: "marketplace",
    confidence: "partially_verified",
    description: "PME Cake Drum Board is a rigid, silver-finish round drum board from PME's Sugarcraft range, replacing an R1-proposed listing whose brand could not be confirmed.",
    replacementNote: "Replaces the R1-proposed \"Round Silver Cake Boards (18-Inch, Pack of 6)\" listing, whose manufacturer/brand attribution could not be confirmed from available sources. PME's brand identity is already independently verified elsewhere in this catalog (PME Supatube, PME Edible Sugar Pearls).",
  },
  {
    id: "prod_real_cake_craft_shop_board",
    slug: "cake-craft-shop-silver-round-cake-board",
    brand: "Cake Craft Shop",
    brandId: "brand_cake_craft_shop",
    dept: DEPARTMENTS.packaging,
    cat: "cat_boards_bases",
    subcat: "subcat_cake_board",
    family: "packaging",
    title: "Silver Round Cake Board (6-Pack)",
    subcategoryLabel: "Silver round cake board",
    productType: "packaging",
    variants: [{ sku: "CCS-BRD-0006", pack: { kind: "count", value: 6, unit: "count", canonicalValue: 6, canonicalUnit: "count", label: "6-inch, pack of 6" }, priceInr: 180, availability: "available" }],
    imageSlug: "cake-craft-shop-board",
    imageSourceUrl: "https://www.cakecraftshop.in/shop/packaging/cake-boards/silver-round-cake-board/",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "This silver round cake board is sold directly by Cake Craft Shop, an Indian cake-decorating tools and supplies retailer, as a base for presenting finished cakes.",
  },
  {
    id: "prod_real_bakers_mart_window_box",
    slug: "bakers-mart-tall-corrugated-window-cake-box",
    brand: "The Baker's Mart",
    brandId: "brand_bakers_mart",
    dept: DEPARTMENTS.packaging,
    cat: "cat_boxes",
    subcat: "subcat_window_box",
    family: "packaging",
    title: "Tall Corrugated Window Cake Box",
    subcategoryLabel: "Corrugated cake box with window",
    productType: "packaging",
    variants: [{ sku: "TBM-BOX-0001", pack: { kind: "count", value: 1, unit: "box", canonicalValue: 1, canonicalUnit: "box", label: "1 box (dimensions not stated)" }, priceInr: 60, availability: "available" }],
    imageSlug: "bakers-mart-window-box",
    imageSourceUrl: "https://www.thebakersmart.in/product/30089102/Tall-Cake-Box----Corrugated---Window-Box",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "This tall corrugated cake box with a display window is sold by The Baker's Mart, an Erode-based Indian bakery-supplies retailer, for packaging taller cakes.",
  },
  {
    id: "prod_real_eco_bags_cake_box",
    slug: "eco-bags-india-cake-box-with-window",
    brand: "Eco Bags India",
    brandId: "brand_eco_bags_india",
    dept: DEPARTMENTS.packaging,
    cat: "cat_boxes",
    subcat: "subcat_cake_box",
    family: "packaging",
    title: "Cake Box with Window",
    subcategoryLabel: "Window cake box",
    productType: "packaging",
    variants: [{ sku: "EBI-BOX-0001", pack: { kind: "count", value: 1, unit: "box", canonicalValue: 1, canonicalUnit: "box", label: "8×8×4 in · fits ~1 kg cake" }, priceInr: 28, availability: "available" }],
    imageSlug: "eco-bags-cake-box",
    imageSourceUrl: "https://ecobags.in/brown-cake-box-with-window-1-kg-8x8x4-in/",
    imageSourceType: "manufacturer",
    confidence: "verified",
    description: "This brown cake box with a display window is sold directly by Eco Bags India for packaging bakery items up to about 1kg, with customization available.",
  },
  {
    id: "prod_real_famous_packaging_box",
    slug: "famous-packaging-window-bakery-box",
    brand: "Famous Packaging",
    brandId: "brand_famous_packaging",
    dept: DEPARTMENTS.packaging,
    cat: "cat_boxes",
    subcat: "subcat_window_box",
    family: "packaging",
    title: "Window Bakery Box",
    subcategoryLabel: "Curved window bakery/cake box",
    productType: "packaging",
    variants: [{ sku: "FPK-BOX-0001", pack: { kind: "count", value: 1, unit: "box", canonicalValue: 1, canonicalUnit: "box", label: "1 box (dimensions not itemized)" }, priceInr: 35, availability: "available" }],
    imageSlug: "famous-packaging-window-box",
    imageSourceUrl: "https://www.indiamart.com/famous-packaging/window-bakery-boxes.html",
    imageSourceType: "authorized_distributor",
    confidence: "partially_verified",
    description: "Famous Packaging, a Mumbai-based packaging wholesaler, lists a curved-window bakery box under its Window Bakery Boxes product line.",
  },
  {
    id: "prod_real_pirsq_cake_box",
    slug: "pirsq-cake-box-with-logo-printing",
    brand: "Pirsq",
    brandId: "brand_pirsq",
    dept: DEPARTMENTS.packaging,
    cat: "cat_boxes",
    subcat: "subcat_cake_box",
    family: "packaging",
    title: "Cake Box with Logo Printing",
    subcategoryLabel: "Custom-printed cake packaging box",
    productType: "packaging",
    variants: [{ sku: "PSQ-BOX-0001", pack: { kind: "count", value: 1, unit: "box", canonicalValue: 1, canonicalUnit: "box", label: "1 box (customizable size)" }, priceInr: 45, availability: "available" }],
    imageSlug: "pirsq-cake-box",
    imageSourceUrl: "https://www.pirsq.com/cake-box/",
    imageSourceType: "marketplace",
    confidence: "partially_verified",
    description: "Pirsq is a supplier platform for paper cake and bakery boxes across India, offering cake boxes with window and logo-printing options for bakeries and cafes.",
  },
];
