const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'), manifestPath=path.join(root,'Catalog_Asset_Manifest.json');
const fail=(m)=>{throw new Error(m)}, hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function dimensions(p){const b=fs.readFileSync(p);if(p.endsWith('.svg')){const s=b.toString('utf8',0,500),w=Number(s.match(/\bwidth="(\d+)"/)?.[1]),h=Number(s.match(/\bheight="(\d+)"/)?.[1]);if(!w||!h)fail(`Unreadable SVG dimensions ${p}`);return{width:w,height:h};}if(p.endsWith('.png')){if(b.toString('hex',0,8)!=='89504e470d0a1a0a')fail(`Invalid PNG ${p}`);return{width:b.readUInt32BE(16),height:b.readUInt32BE(20)};}if(p.endsWith('.webp')){if(b.toString('ascii',0,4)!=='RIFF'||b.toString('ascii',8,12)!=='WEBP')fail(`Invalid WebP ${p}`);const kind=b.toString('ascii',12,16);if(kind==='VP8X')return{width:1+b.readUIntLE(24,3),height:1+b.readUIntLE(27,3)};if(kind==='VP8 '){const i=20;return{width:b.readUInt16LE(i+6)&0x3fff,height:b.readUInt16LE(i+8)&0x3fff};}if(kind==='VP8L'){const bits=b.readUInt32LE(21);return{width:(bits&0x3fff)+1,height:((bits>>14)&0x3fff)+1};}fail(`Unsupported WebP chunk ${kind} ${p}`);}fail(`Unsupported format ${p}`);}
(async()=>{const m=JSON.parse(fs.readFileSync(manifestPath));if(m.manifest_schema_version!=='1.0.0')fail('Unsupported manifest schema');
 const productData=JSON.parse(fs.readFileSync(path.join(root,'Product_Master_Data.json'))),skuData=JSON.parse(fs.readFileSync(path.join(root,'SKU_Variant_Data.json'))),recipeData=JSON.parse(fs.readFileSync(path.join(root,'Recipe_Master_Data.json')));
 const productIds=new Set(productData.products.map(x=>x.id)),variantIds=new Set(skuData.variants.map(x=>x.id)),skus=new Set(skuData.variants.map(x=>x.sku)),recipeIds=new Set(recipeData.recipes.map(x=>x.id));
 if(m.catalog_scope.product_count!==24||m.catalog_scope.recipe_count!==6||m.catalog_scope.department_visual_count!==7)fail('Required coverage count mismatch');
 const ids=new Set(),paths=new Set();for(const r of m.records){if(ids.has(r.asset_id))fail(`Duplicate ${r.asset_id}`);ids.add(r.asset_id);if(r.status!=='approved')fail(`Unapproved ${r.asset_id}`);if(r.approval.decision!=='approved_for_phase_5b_review')fail(`Bad approval ${r.asset_id}`);if(r.prohibited_claim_review.result!=='passed')fail(`Claim review failed ${r.asset_id}`);if(!r.alt_text.text)fail(`Missing alt ${r.asset_id}`);
  if(r.relationships.product_ids.some(x=>!productIds.has(x))||r.relationships.variant_ids.some(x=>!variantIds.has(x))||r.relationships.skus.some(x=>!skus.has(x))||r.relationships.recipe_ids.some(x=>!recipeIds.has(x)))fail(`Unresolved data relationship ${r.asset_id}`);
  for(const f of [r.master,...r.derivatives]){const p=path.join(root,f.path);if(!fs.existsSync(p))fail(`Missing ${f.path}`);paths.add(f.path);if(hash(p)!==f.checksum.value)fail(`Checksum drift ${f.path}`);const md=dimensions(p);if(md.width!==f.width||md.height!==f.height)fail(`Dimension mismatch ${f.path}`);}
 }
 const products=m.records.filter(r=>r.asset_family==='product_packshot'&&r.role==='primary');if(products.length!==24)fail('Need 24 product primaries');if(products.some(r=>!['primary','thumbnail'].every(p=>r.derivatives.some(d=>d.purpose===p))))fail('Product derivative gap');
 const variants=m.records.filter(r=>r.role==='variant');
 const expectedVisualVariants=skuData.variants;
 const variantsById=new Map(expectedVisualVariants.map(item=>[item.id,item]));
 const mappedVariantIds=new Set(variants.flatMap(r=>r.relationships.variant_ids));
 const mappedSkus=new Set(variants.flatMap(r=>r.relationships.skus));
 if(variants.length!==expectedVisualVariants.length||variants.some(r=>r.relationships.product_ids.length!==1||r.relationships.variant_ids.length!==1||r.relationships.skus.length!==1))fail('Variant-owned media count or atomicity gap');
 for(const item of expectedVisualVariants)if(!mappedVariantIds.has(item.id)||!mappedSkus.has(item.sku))fail(`Missing visually changing variant media ${item.id} / ${item.sku}`);
 for(const record of variants){const item=variantsById.get(record.relationships.variant_ids[0]);if(!item||record.relationships.product_ids[0]!==item.parent_product_id||record.relationships.skus[0]!==item.sku)fail(`Variant tuple mismatch ${record.asset_id}`);if(!record.alt_text.text.includes(item.normalized_sell_quantity.display_label)||!record.alt_text.text.includes(item.sku))fail(`Variant alt omits exact quantity or SKU ${record.asset_id}`);if(!['variant_primary','variant_thumbnail'].every(purpose=>record.derivatives.some(d=>d.purpose===purpose)))fail(`Variant derivative gap ${record.asset_id}`);}
 if(variants.some(r=>r.source_method!=='deterministic_svg_pack_and_manual_label_composite'))fail('Product variant is missing deterministic label provenance');
 const productMasters=m.records.filter(r=>r.asset_family==='product_packshot').map(r=>fs.readFileSync(path.join(root,r.master.path),'utf8'));
 if(productMasters.some(svg=>!svg.includes('PORTFOLIO DEMO')||!svg.includes('PANTRYFORM')))fail('Visible deterministic disclosure/label gap');
 const recipes=m.records.filter(r=>r.asset_family==='recipe');if(recipes.length!==6||recipes.some(r=>!['recipe_hero','recipe_listing'].every(p=>r.derivatives.some(d=>d.purpose===p))))fail('Recipe crop gap');
 const depts=new Set(m.records.filter(r=>r.asset_family==='department').flatMap(r=>r.relationships.department_ids));if(depts.size!==7)fail('Department relationship coverage gap');
 const editorial=m.records.filter(r=>r.asset_family==='recipe'||r.asset_family==='department');
 if(editorial.length!==13||editorial.some(r=>r.source_method!=='generated_source_with_deterministic_responsive_crops'||r.master.format!=='png'||!r.master.path.startsWith('masters/generated/')||!r.generation?.prompt_reference||r.generation.visible_generated_typography!==false))fail('Generated editorial provenance gap');
 if(!fs.existsSync(path.join(root,'Editorial_Generation_Prompts.md')))fail('Editorial prompt lineage file missing');
 function walk(relative){for(const entry of fs.readdirSync(path.join(root,relative),{withFileTypes:true})){const next=`${relative}/${entry.name}`;if(entry.isDirectory())walk(next);else if(!paths.has(next))fail(`Orphan file ${next}`)}}
 for(const dir of ['masters','exports'])walk(dir);
 console.log(JSON.stringify({status:'PASS',records:m.records.length,productPrimaries:products.length,variantMedia:variants.length,recipes:recipes.length,departmentVisuals:m.catalog_scope.department_visual_count,departmentRelationships:depts.size,filesChecked:paths.size},null,2));
})().catch(e=>{console.error(`FAIL: ${e.message}`);process.exit(1)});
