const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'), manifestPath=path.join(root,'Catalog_Asset_Manifest.json');
const fail=(m)=>{throw new Error(m)}, hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function dimensions(p){const b=fs.readFileSync(p);if(p.endsWith('.svg')){const s=b.toString('utf8',0,500),w=Number(s.match(/\bwidth="(\d+)"/)?.[1]),h=Number(s.match(/\bheight="(\d+)"/)?.[1]);if(!w||!h)fail(`Unreadable SVG dimensions ${p}`);return{width:w,height:h};}if(p.endsWith('.webp')){if(b.toString('ascii',0,4)!=='RIFF'||b.toString('ascii',8,12)!=='WEBP')fail(`Invalid WebP ${p}`);const kind=b.toString('ascii',12,16);if(kind==='VP8X')return{width:1+b.readUIntLE(24,3),height:1+b.readUIntLE(27,3)};if(kind==='VP8 '){const i=20;return{width:b.readUInt16LE(i+6)&0x3fff,height:b.readUInt16LE(i+8)&0x3fff};}if(kind==='VP8L'){const bits=b.readUInt32LE(21);return{width:(bits&0x3fff)+1,height:((bits>>14)&0x3fff)+1};}fail(`Unsupported WebP chunk ${kind} ${p}`);}fail(`Unsupported format ${p}`);}
(async()=>{const m=JSON.parse(fs.readFileSync(manifestPath));if(m.manifest_schema_version!=='1.0.0')fail('Unsupported manifest schema');
 const productData=JSON.parse(fs.readFileSync(path.join(root,'Product_Master_Data.json'))),skuData=JSON.parse(fs.readFileSync(path.join(root,'SKU_Variant_Data.json'))),recipeData=JSON.parse(fs.readFileSync(path.join(root,'Recipe_Master_Data.json')));
 const productIds=new Set(productData.products.map(x=>x.id)),variantIds=new Set(skuData.variants.map(x=>x.id)),skus=new Set(skuData.variants.map(x=>x.sku)),recipeIds=new Set(recipeData.recipes.map(x=>x.id));
 if(m.catalog_scope.product_count!==24||m.catalog_scope.recipe_count!==6||m.catalog_scope.department_visual_count!==7)fail('Required coverage count mismatch');
 const ids=new Set(),paths=new Set();for(const r of m.records){if(ids.has(r.asset_id))fail(`Duplicate ${r.asset_id}`);ids.add(r.asset_id);if(r.status!=='approved')fail(`Unapproved ${r.asset_id}`);if(r.approval.decision!=='approved_for_phase_5b_review')fail(`Bad approval ${r.asset_id}`);if(r.prohibited_claim_review.result!=='passed')fail(`Claim review failed ${r.asset_id}`);if(!r.alt_text.text)fail(`Missing alt ${r.asset_id}`);
  if(r.relationships.product_ids.some(x=>!productIds.has(x))||r.relationships.variant_ids.some(x=>!variantIds.has(x))||r.relationships.skus.some(x=>!skus.has(x))||r.relationships.recipe_ids.some(x=>!recipeIds.has(x)))fail(`Unresolved data relationship ${r.asset_id}`);
  for(const f of [r.master,...r.derivatives]){const p=path.join(root,f.path);if(!fs.existsSync(p))fail(`Missing ${f.path}`);paths.add(f.path);if(hash(p)!==f.checksum.value)fail(`Checksum drift ${f.path}`);const md=dimensions(p);if(md.width!==f.width||md.height!==f.height)fail(`Dimension mismatch ${f.path}`);}
 }
 const products=m.records.filter(r=>r.asset_family==='product_packshot'&&r.role==='primary');if(products.length!==24)fail('Need 24 product primaries');if(products.some(r=>!['primary','thumbnail'].every(p=>r.derivatives.some(d=>d.purpose===p))))fail('Product derivative gap');
 const variants=m.records.filter(r=>r.role==='variant');if(variants.length<6||variants.some(r=>!r.relationships.variant_ids.length||!r.relationships.skus.length))fail('Variant-owned media gap');
 const recipes=m.records.filter(r=>r.asset_family==='recipe');if(recipes.length!==6||recipes.some(r=>!['recipe_hero','recipe_listing'].every(p=>r.derivatives.some(d=>d.purpose===p))))fail('Recipe crop gap');
 const depts=new Set(m.records.filter(r=>r.asset_family==='department').flatMap(r=>r.relationships.department_ids));if(depts.size!==7)fail('Department relationship coverage gap');
 for(const dir of ['masters','exports'])for(const f of fs.readdirSync(path.join(root,dir))){if(!paths.has(`${dir}/${f}`))fail(`Orphan file ${dir}/${f}`)}
 console.log(JSON.stringify({status:'PASS',records:m.records.length,productPrimaries:products.length,variantMedia:variants.length,recipes:recipes.length,departmentVisuals:m.catalog_scope.department_visual_count,departmentRelationships:depts.size,filesChecked:paths.size},null,2));
})().catch(e=>{console.error(`FAIL: ${e.message}`);process.exit(1)});
