globalThis.__phase5bErrors=[];
addEventListener('error',e=>globalThis.__phase5bErrors.push(e.message||'resource error'));
addEventListener('unhandledrejection',e=>globalThis.__phase5bErrors.push(String(e.reason)));
const {departments,products,recipes,recipeMappings}=globalThis.PF5B;
const canonicalProduct=id=>products.find(product=>product.canonicalId===id);
const E='../../production_artifacts/05_catalog_production/exports/';
const q=new URLSearchParams(location.search), view=q.get('view')||'contact';
if(q.get('text')==='200')document.documentElement.classList.add('text-200');
if(q.get('images')==='off')document.documentElement.classList.add('images-off');
if(q.get('mode')==='grayscale')document.documentElement.classList.add('grayscale');
const art=(material,label,extra='',src='')=>{src=src.replace(/variant_(bcp-[^_]+)-v1_primary/,'variant_$1_v1_primary');let image='';if(src.includes('_department_')&&src.includes('_wide_')){const mobile=src.replace('_wide_1536x1024','_square_800');image=`<picture><source media="(max-width:520px)" srcset="${mobile}"><img src="${src}" alt="${label}" onerror="this.hidden=true;this.closest('.asset').classList.add('failed')"></picture>`}else if(src.includes('_recipe_demo-cocoa-celebration-cake_hero_')){const mobile=src.replace('_hero_1536x1024','_listing_800x600');image=`<picture><source media="(max-width:520px)" srcset="${mobile}"><img src="${src}" alt="${label}" onerror="this.hidden=true;this.closest('.asset').classList.add('failed')"></picture>`}else if(src){image=`<img src="${src}" alt="${label}" onerror="this.hidden=true;this.parentElement.classList.add('failed')">`}return `<figure class="asset ${material} ${extra}">${image}<span class="asset-fallback">Image unavailable</span></figure>`};
const productSrc=(p,purpose='thumbnail')=>p[purpose];
const departmentSrc=(d,purpose='square')=>d[purpose];
const card=p=>`<article class="product-card" data-dept="${p.department}" data-title="${p.title.toLowerCase()}">${art(p.material,`${p.title}, shown as original portfolio-demo packaging.`,'',productSrc(p))}<p class="kicker">${p.brand} · ${p.category}</p><h2>${p.title}</h2><p class="measure">${p.pack}</p><div class="card-foot"><strong>${p.price}</strong><span class="status ${p.status.replaceAll(' ','-')}">${p.status}</span></div><small>${p.sku} · fictional demo</small></article>`;
const recipeCard=r=>`<article class="recipe-card">${art(r.material,`${r.title}, illustrative original demo recipe presentation.`,'wide',r.listing)}<p class="kicker">Original demo recipe · ${r.category}</p><h2>${r.title}</h2><p>${r.yieldLabel} · illustrative presentation, not a guaranteed result.</p></article>`;
const views={
  home:()=>`<section class="home-hero"><div class="home-copy"><p class="kicker">Measured ingredients · joyful making</p><h1>From pantry measure to finished bake.</h1><p>Explore precise packs, material-led departments and original demo recipes in one measured journey.</p><div class="hero-actions"><a href="?view=plp">Shop exact packs</a><a href="?view=recipes">Plan from a recipe</a></div></div>${art('cocoa','Cocoa Celebration Cake, an illustrative original demo recipe presentation.','home-art',recipes[0].hero)}</section><section class="ingredient-ribbon"><span>01 · raw ingredient</span><span>02 · exact measure</span><span>03 · method</span><span>04 · finished bake</span></section><section><div class="section-head"><h2>Read the pantry by material</h2><p>Not just colour: form, texture and use</p></div><div class="home-departments">${departments.filter(d=>d.id!=='recipes').slice(0,4).map((d,i)=>`<article class="dept-${i}">${art(d.material,`${d.name} department material study.`,'wide',departmentSrc(d,i===0?'wide':'square'))}<span class="axis">0${i+1}</span><h3>${d.name}</h3><p>${d.summary}</p></article>`).join('')}</div></section><section class="editorial-bridge">${art('orange','Orange Glaze Loaf, illustrative original demo recipe presentation.','wide',recipes.find(r=>r.id==='orange-glaze-loaf').hero)}<div><p class="kicker">Recipe → supplies</p><h2>A loaf, translated into the smallest sufficient packs.</h2><p>Required amount, selected pack and expected leftover remain visible before anything enters the demo cart.</p><a href="?view=mappings">Review recipe mapping</a></div></section>`,
  contact:()=>`<section class="intro"><p class="kicker">Asset production desk · coverage view</p><h1>One pantry, many material voices.</h1><p>Review hierarchy, crop resilience and assortment coherence before production handoff. Asset tiles are deterministic placement studies, not final product photographs.</p></section><section><div class="section-head"><h2>30 primary records</h2><p>24 product families · 6 original demo recipes</p></div><div class="contact-grid">${products.map(card).join('')}${recipes.map(recipeCard).join('')}</div></section>`,
  assets:()=>`<section class="intro compact"><p class="kicker">Manifest-complete evidence</p><h1>Every final derivative, in one place.</h1><p>Loaded directly from the final asset manifest. Use <code>&amp;mode=grayscale</code> for silhouette and contrast review.</p></section><p id="asset-count" role="status">Loading manifest-backed assets…</p><div id="manifest-grid" class="manifest-grid" aria-busy="true"></div>`,
  departments:()=>`<section class="intro"><p class="kicker">Eight-part pantry atlas</p><h1>Discover by making material.</h1><p>Each department keeps its own silhouette and material cue while sharing a measured cropping system.</p></section><div class="department-atlas">${departments.map((d,i)=>`<article><span class="axis">0${i+1}</span>${art(d.material,`${d.name} department visual, an original geometric portfolio-demo composition.`,'wide',departmentSrc(d,'wide'))}<h2>${d.name}</h2><p>${d.summary}</p><strong>${d.id==='recipes'?recipes.length:products.filter(p=>p.department===d.id).length} review records</strong></article>`).join('')}</div>`,
  plp:()=>`<section class="intro compact"><p class="kicker">Search and listing density</p><h1>Find the exact form and pack.</h1></section><div class="discovery"><aside><h2>Refine</h2><label><input type="checkbox"> Available in demo</label><label><input type="checkbox"> Ingredients</label><label><input type="checkbox"> Chocolate</label><label><input type="checkbox"> Packaging</label><button type="button">Clear filters</button></aside><section><div class="search-row"><label>Search products<input id="search" type="search" placeholder="Try cocoa or 500 g"></label><label>Department<select id="dept"><option value="">All departments</option>${departments.filter(d=>d.id!=='recipes').map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}</select></label><p id="result-count" role="status">24 results</p></div><div id="product-grid" class="product-grid">${products.map(card).join('')}</div><div id="empty" class="empty" hidden><h2>No exact pantry match</h2><p>Clear the current search or browse all departments. Your query remains available to edit.</p></div></section></div>`,
  products:()=>`<section class="intro compact"><p class="kicker">Full product coverage</p><h1>24 parent products, one scan.</h1><p>Brand, family, selected pack, INR price, demo availability and SKU remain visible at review density.</p></section><div class="table-wrap"><table><thead><tr><th>#</th><th>Asset</th><th>Product</th><th>Department</th><th>Pack</th><th>Demo price</th><th>State / SKU</th></tr></thead><tbody>${products.map(p=>`<tr><td>${String(p.index).padStart(2,'0')}</td><td>${art(p.material,`${p.title}, portfolio-demo packaging thumbnail.`,'',productSrc(p))}</td><td><strong>${p.title}</strong><small>${p.brand} · ${p.category}</small></td><td>${departments.find(d=>d.id===p.department).name}</td><td>${p.pack}</td><td>${p.price}</td><td><span class="status ${p.status.replaceAll(' ','-')}">${p.status}</span><small>${p.sku}</small></td></tr>`).join('')}</tbody></table></div>`,
  variants:()=>{const cocoa=products.find(p=>p.canonicalId==='prod_demo_baking_cocoa'),selected=cocoa.variants.find(v=>v.sku==='ML-BCP-500');return `<section class="intro compact"><p class="kicker">Pack-family and axis proof</p><h1>Choose the measure, then see the facts.</h1></section><section class="variant-stage"><div class="pack-family">${cocoa.variants.map((v,i)=>art('cocoa',`${cocoa.brand} ${cocoa.title}, ${v.pack} prototype pouch.`,`pack p${i+1}`,v.primary)).join('')}</div><div class="buybox"><p class="kicker">${cocoa.brand} · Cocoa</p><h2>${cocoa.title}</h2><fieldset><legend>Pack weight</legend>${cocoa.variants.map(v=>`<button class="variant" aria-pressed="${v.id===selected.id}" data-price="${v.price}" data-sku="${v.sku}">${v.pack}</button>`).join('')}</fieldset><p id="selection" role="status">${selected.pack} selected · ${selected.price} · ${selected.sku}</p><dl><dt>Ingredients</dt><dd>Information not provided</dd><dt>Allergens</dt><dd>Information not provided</dd><dt>Storage</dt><dd>Information not provided</dd></dl><button>Add to demo cart</button><small>Fictional demo price and availability. No real order.</small></div></section>`},
  pdp:()=>{const cocoa=products.find(p=>p.canonicalId==='prod_demo_baking_cocoa'),selected=cocoa.variants.find(v=>v.sku==='ML-BCP-500'),map=recipeMappings[0].items.find(i=>i.productId===cocoa.id);return `<section class="pdp"><div class="pdp-gallery">${art('cocoa',`${cocoa.brand} ${cocoa.title}, ${selected.pack} fictional portfolio-demo pouch.`,'pdp-primary',selected.primary)}<div class="pdp-thumbs">${cocoa.variants.map(v=>`${art('cocoa',`${v.pack} pack thumbnail.`,'',v.thumbnail)}<span>${v.pack}</span>`).join('')}</div></div><div class="buybox pdp-buy"><p class="kicker">${cocoa.brand} · Cocoa</p><h1>${cocoa.title}</h1><p class="pdp-price">${selected.price} <small>fictional demo price</small></p><p>Selected: <strong>${selected.pack}</strong> · SKU ${selected.sku}</p><fieldset><legend>Choose pack weight</legend>${cocoa.variants.map(v=>`<button class="variant" aria-pressed="${v.id===selected.id}" data-price="${v.price}" data-sku="${v.sku}">${v.pack}</button>`).join('')}</fieldset><p id="selection" role="status">${selected.pack} selected · ${selected.price} · ${selected.sku}</p><button class="add-wide">Add selected pack to demo cart</button><dl><dt>Form</dt><dd>${cocoa.content.family_attributes.form.value}</dd><dt>Ingredients</dt><dd>Information not provided</dd><dt>Allergens</dt><dd>Information not provided</dd><dt>Storage</dt><dd>Information not provided</dd></dl><small>Portfolio prototype. No real availability, payment or order.</small></div></section><section class="pdp-method"><span>${map.required.value} ${map.required.canonical_unit}</span><div><p class="kicker">Recipe connection</p><h2>The selected packs cover one Cocoa Celebration Cake mapping.</h2><p>Recipe requirement ${map.required.value} ${map.required.canonical_unit} · selected ${map.selectedPacks.map(p=>p.pack).join(' + ')} · expected leftover ${map.leftoverCanonicalQuantity.value} ${map.leftoverCanonicalQuantity.unit}.</p></div><a href="?view=mappings">See the full mapping</a></section>`},
  recipes:()=>`<section class="intro"><p class="kicker">Recipe editorial family</p><h1>Inspiration keeps its measurements.</h1><p>Six distinct crops balance finished-bake context with raw ingredient and method cues.</p></section><div class="recipe-grid">${recipes.map(recipeCard).join('')}</div>`,
  mappings:()=>{const recipe=recipes[0],mapping=recipeMappings.find(r=>r.recipeId===recipe.canonicalId),eligible=mapping.items.filter(i=>i.autoAddEligible).length;return `<section class="intro compact"><p class="kicker">Recipe → reviewed supply</p><h1>Required, selected, purchased, leftover.</h1><p>All ${recipeMappings.reduce((n,r)=>n+r.items.length,0)} canonical recipe lines are represented in the browser fixture; this view shows the selected recipe’s mapped, optional, pantry and unmapped states.</p></section><section class="mapping"><div class="recipe-lead">${art('cocoa',`${recipe.title}, illustrative original demo recipe presentation.`,'wide',recipe.hero)}<h2>${recipe.title}</h2><p>${recipe.yieldLabel} · mapping review only</p></div><div class="mapping-list">${mapping.items.map((m,i)=>{const p=products.find(x=>x.id===m.productId),required=`${m.required.value} ${m.required.canonical_unit}`;if(!p)return `<article><span class="axis">${String(i+1).padStart(2,'0')}</span><div><h3>${m.name}</h3><p>Required <strong>${required}</strong> · no bounded catalog mapping</p><small>Unmapped pantry requirement · not auto-added</small></div><label><input type="checkbox" disabled> No sellable SKU</label></article>`;const selected=m.selectedPacks.map(x=>x.pack).join(' + ');return `<article><span class="axis">${String(i+1).padStart(2,'0')}</span>${art(p.material,`${p.title}, portfolio-demo packaging thumbnail.`,'',productSrc(p))}<div><h3>${m.name}</h3><p>Required <strong>${required}</strong> → selected <strong>${selected}</strong></p><small>Purchased ${m.purchasedCanonicalQuantity.value} ${m.purchasedCanonicalQuantity.unit} · leftover ${m.leftoverCanonicalQuantity.value} ${m.leftoverCanonicalQuantity.unit}${m.optional?' · optional':m.pantryDefault==='suggest_owned'?' · pantry check':''}</small></div><label><input type="checkbox" ${m.autoAddEligible?'checked':'disabled'}> ${m.autoAddEligible?`Add ${m.selectedPacks.map(x=>x.sku).join(' + ')}`:'Not auto-added'}</label></article>`}).join('')}<div class="mapping-total"><p>${eligible} eligible canonical mappings selected</p><button>Add selected packs to demo cart</button></div></div></section>`},
  states:()=>{const cocoa=products.find(p=>p.canonicalId==='prod_demo_baking_cocoa'),selected=cocoa.variants.find(v=>v.sku==='ML-BCP-500');return `<section class="intro compact"><p class="kicker">Resilience contract</p><h1>Facts survive visual failure.</h1></section><div class="state-grid"><article><div class="asset failed" role="img" aria-label="Image unavailable"><span>Image unavailable</span></div><h2>${cocoa.title}</h2><p>${selected.pack} · ${selected.sku} · ${selected.price}</p><p>Ingredients, allergens and storage: Information not provided.</p></article><article class="skeleton" aria-label="Loading product"><i></i><b></b><b></b><b></b><span>Loading product facts…</span></article><article><div class="notice"><strong>That pack is unavailable</strong><p>Your ${selected.pack} selection was kept. Choose another pack; nothing was added automatically.</p><button>Review pack sizes</button></div></article><article><div class="notice error"><strong>Images could not be loaded</strong><p>Product names, packs, prices and controls remain available.</p><button>Try images again</button></div></article></div>`},
  stress:()=>{const box=canonicalProduct('prod_window_cake_box'),variant=box.variants[0],facts=box.content.critical_facts;return `<section class="intro compact"><p class="kicker">Content-fit and narrow-density test</p><h1>Canonical facts must wrap, not vanish.</h1></section><div class="stress-grid"><article>${art('box',`${box.title}, shown as original portfolio-demo packaging.`,'',box.primary)}<p class="kicker">${box.brand} · ${box.category}</p><h2>${box.title}</h2><p class="measure">${variant.pack}</p><p>${box.content.short_description}</p><strong>${variant.price}</strong><small>${variant.sku} · fictional demo</small></article><article><h2>Critical facts</h2><dl><dt>Ingredients</dt><dd>${facts.ingredients.status.replaceAll('_',' ')}</dd><dt>Allergens</dt><dd>${facts.allergens.status.replaceAll('_',' ')}</dd><dt>Storage</dt><dd>${facts.storage.status.replaceAll('_',' ')}</dd><dt>Availability</dt><dd>${variant.status}</dd></dl><button>Add to demo cart</button></article></div>`}
};
document.querySelector('#main').innerHTML=(views[view]||views.contact)();
document.querySelectorAll('nav a').forEach(a=>a.toggleAttribute('aria-current',new URL(a.href).searchParams.get('view')===view));
document.querySelector('.nav-toggle').addEventListener('click',e=>{const open=e.currentTarget.getAttribute('aria-expanded')==='true';e.currentTarget.setAttribute('aria-expanded',String(!open));document.querySelector('#review-nav').classList.toggle('open',!open)});
const filter=()=>{const term=(document.querySelector('#search')?.value||'').trim().toLowerCase(),dept=document.querySelector('#dept')?.value||'';let n=0;document.querySelectorAll('#product-grid .product-card').forEach(el=>{const show=(!term||el.dataset.title.includes(term)||el.textContent.toLowerCase().includes(term))&&(!dept||el.dataset.dept===dept);el.hidden=!show;if(show)n++});if(document.querySelector('#result-count'))document.querySelector('#result-count').textContent=`${n} result${n===1?'':'s'}`;if(document.querySelector('#empty'))document.querySelector('#empty').hidden=n!==0};
document.querySelector('#search')?.addEventListener('input',filter);document.querySelector('#dept')?.addEventListener('change',filter);
document.querySelectorAll('.variant').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.variant').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');document.querySelector('#selection').textContent=`${b.textContent} selected · ${b.dataset.price} · ${b.dataset.sku}`}));
if(view==='assets')fetch('../../production_artifacts/05_catalog_production/Catalog_Asset_Manifest.json')
  .then(r=>{if(!r.ok)throw Error(`Manifest request failed: ${r.status}`);return r.json()})
  .then(m=>{
    const derivatives=m.records.flatMap((record,recordIndex)=>(record.derivatives||[]).map(d=>({record,recordIndex,d}))).filter(x=>/\.(webp|png|jpe?g|svg)$/i.test(x.d.path));
    document.querySelector('#asset-count').textContent=`${derivatives.length} manifest-backed visual derivatives`;
    document.querySelector('#manifest-grid').innerHTML=derivatives.map(({record,recordIndex,d},i)=>{const id=record.asset_id||record.assetId||record.id||`Record ${recordIndex+1}`;return `<article>${art('',`Manifest asset ${i+1}: ${id}.`,'',`../../production_artifacts/05_catalog_production/${d.path}`)}<strong>${id}</strong><small>${d.path.split('/').pop()}</small></article>`}).join('');
    document.querySelector('#manifest-grid').setAttribute('aria-busy','false');
  })
  .catch(e=>{globalThis.__phase5bErrors.push(e.message);document.querySelector('#asset-count').textContent='Manifest assets could not be loaded';document.querySelector('#manifest-grid').setAttribute('aria-busy','false')});
