globalThis.__phase5bErrors=[];
addEventListener('error',e=>globalThis.__phase5bErrors.push(e.message||'resource error'));
addEventListener('unhandledrejection',e=>globalThis.__phase5bErrors.push(String(e.reason)));
const {departments,products,recipes}=globalThis.PF5B;
const E='../../production_artifacts/05_catalog_production/exports/';
const q=new URLSearchParams(location.search), view=q.get('view')||'contact';
if(q.get('text')==='200')document.documentElement.classList.add('text-200');
if(q.get('images')==='off')document.documentElement.classList.add('images-off');
const art=(material,label,extra='',src='')=>{src=src.replace(/variant_(bcp-[^_]+)-v1_primary/,'variant_$1_v1_primary');let image='';if(src.includes('_department_')&&src.includes('_wide_')){const mobile=src.replace('_wide_1536x1024','_square_800');image=`<picture><source media="(max-width:520px)" srcset="${mobile}"><img src="${src}" alt="${label}" onerror="this.hidden=true;this.closest('.asset').classList.add('failed')"></picture>`}else if(src.includes('_recipe_demo-cocoa-celebration-cake_hero_')){const mobile=src.replace('_hero_1536x1024','_listing_800x600');image=`<picture><source media="(max-width:520px)" srcset="${mobile}"><img src="${src}" alt="${label}" onerror="this.hidden=true;this.closest('.asset').classList.add('failed')"></picture>`}else if(src){image=`<img src="${src}" alt="${label}" onerror="this.hidden=true;this.parentElement.classList.add('failed')">`}return `<figure class="asset ${material} ${extra}">${image}<span class="asset-fallback">Image unavailable</span></figure>`};
const productSrc=(p,purpose='thumbnail')=>`${E}asset_pf5b_prod_${p.assetSlug}_${purpose}_${purpose==='thumbnail'?'480':'1200'}_v1.webp`;
const departmentSrc=(d,purpose='square')=>d.id==='recipes'?`${E}asset_pf5b_recipe_demo-cocoa-celebration-cake_${purpose==='square'?'listing_800x600':'hero_1536x1024'}_v1.webp`:`${E}asset_pf5b_department_${d.id==='colour-flavour'?'colours-flavours':d.id}_v1_${purpose==='square'?'square_800':'wide_1536x1024'}.webp`;
const card=p=>`<article class="product-card" data-dept="${p.department}" data-title="${p.title.toLowerCase()}">${art(p.material,`${p.title}, shown as original portfolio-demo packaging.`,'',productSrc(p))}<p class="kicker">${p.brand} · ${p.category}</p><h2>${p.title}</h2><p class="measure">${p.pack}</p><div class="card-foot"><strong>${p.price}</strong><span class="status ${p.status.replaceAll(' ','-')}">${p.status}</span></div><small>${p.sku} · fictional demo</small></article>`;
const recipeCard=r=>`<article class="recipe-card">${art(r.material,`${r.title}, illustrative original demo recipe presentation.`,'wide',`${E}asset_pf5b_recipe_${r.assetSlug}_listing_800x600_v1.webp`)}<p class="kicker">Original demo recipe · ${r.category}</p><h2>${r.title}</h2><p>${r.yieldLabel} · illustrative presentation, not a guaranteed result.</p></article>`;
const views={
  contact:()=>`<section class="intro"><p class="kicker">Asset production desk · coverage view</p><h1>One pantry, many material voices.</h1><p>Review hierarchy, crop resilience and assortment coherence before production handoff. Asset tiles are deterministic placement studies, not final product photographs.</p></section><section><div class="section-head"><h2>30 primary records</h2><p>24 product families · 6 original demo recipes</p></div><div class="contact-grid">${products.map(card).join('')}${recipes.map(recipeCard).join('')}</div></section>`,
  departments:()=>`<section class="intro"><p class="kicker">Eight-part pantry atlas</p><h1>Discover by making material.</h1><p>Each department keeps its own silhouette and material cue while sharing a measured cropping system.</p></section><div class="department-atlas">${departments.map((d,i)=>`<article><span class="axis">0${i+1}</span>${art(d.material,`${d.name} department visual, an original geometric portfolio-demo composition.`,'wide',departmentSrc(d,'wide'))}<h2>${d.name}</h2><p>${d.summary}</p><strong>${d.id==='recipes'?recipes.length:products.filter(p=>p.department===d.id).length} review records</strong></article>`).join('')}</div>`,
  plp:()=>`<section class="intro compact"><p class="kicker">Search and listing density</p><h1>Find the exact form and pack.</h1></section><div class="discovery"><aside><h2>Refine</h2><label><input type="checkbox"> Available in demo</label><label><input type="checkbox"> Ingredients</label><label><input type="checkbox"> Chocolate</label><label><input type="checkbox"> Packaging</label><button type="button">Clear filters</button></aside><section><div class="search-row"><label>Search products<input id="search" type="search" placeholder="Try cocoa or 500 g"></label><label>Department<select id="dept"><option value="">All departments</option>${departments.filter(d=>d.id!=='recipes').map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}</select></label><p id="result-count" role="status">24 results</p></div><div id="product-grid" class="product-grid">${products.map(card).join('')}</div><div id="empty" class="empty" hidden><h2>No exact pantry match</h2><p>Clear the current search or browse all departments. Your query remains available to edit.</p></div></section></div>`,
  products:()=>`<section class="intro compact"><p class="kicker">Full product coverage</p><h1>24 parent products, one scan.</h1><p>Brand, family, selected pack, INR price, demo availability and SKU remain visible at review density.</p></section><div class="table-wrap"><table><thead><tr><th>#</th><th>Asset</th><th>Product</th><th>Department</th><th>Pack</th><th>Demo price</th><th>State / SKU</th></tr></thead><tbody>${products.map(p=>`<tr><td>${String(p.index).padStart(2,'0')}</td><td>${art(p.material,`${p.title}, portfolio-demo packaging thumbnail.`,'',productSrc(p))}</td><td><strong>${p.title}</strong><small>${p.brand} · ${p.category}</small></td><td>${departments.find(d=>d.id===p.department).name}</td><td>${p.pack}</td><td>${p.price}</td><td><span class="status ${p.status.replaceAll(' ','-')}">${p.status}</span><small>${p.sku}</small></td></tr>`).join('')}</tbody></table></div>`,
  variants:()=>{const cocoa=products.find(p=>p.id==='baking-cocoa');return `<section class="intro compact"><p class="kicker">Pack-family and axis proof</p><h1>Choose the measure, then see the facts.</h1></section><section class="variant-stage"><div class="pack-family">${[['250 g','bcp-250g-v1'],['500 g','bcp-500g-v1'],['1 kg','bcp-1kg-v1']].map(([x,id],i)=>art('cocoa',`Measureloom Baking cocoa powder, ${x} prototype pouch.`,`pack p${i+1}`,`${E}asset_pf5b_variant_${id}_primary_1200.webp`)).join('')}</div><div class="buybox"><p class="kicker">${cocoa.brand} · Cocoa</p><h2>${cocoa.title}</h2><fieldset><legend>Pack weight</legend>${[['250 g','₹175','ML-BCP-250'],['500 g','₹315','ML-BCP-500'],['1 kg','₹575','ML-BCP-1000']].map((v,i)=>`<button class="variant" aria-pressed="${i===1}" data-price="${v[1]}" data-sku="${v[2]}">${v[0]}</button>`).join('')}</fieldset><p id="selection" role="status">500 g selected · ₹315 · ML-BCP-500</p><dl><dt>Ingredients</dt><dd>Information not provided</dd><dt>Allergens</dt><dd>Information not provided</dd><dt>Storage</dt><dd>Information not provided</dd></dl><button>Add to demo cart</button><small>Fictional demo price and availability. No real order.</small></div></section>`},
  recipes:()=>`<section class="intro"><p class="kicker">Recipe editorial family</p><h1>Inspiration keeps its measurements.</h1><p>Six distinct crops balance finished-bake context with raw ingredient and method cues.</p></section><div class="recipe-grid">${recipes.map(recipeCard).join('')}</div>`,
  mappings:()=>`<section class="intro compact"><p class="kicker">Recipe → reviewed supply</p><h1>Required, selected, purchased, leftover.</h1></section><section class="mapping"><div class="recipe-lead">${art('cocoa','Cocoa Celebration Cake, illustrative original demo recipe presentation.','wide',`${E}asset_pf5b_recipe_demo-cocoa-celebration-cake_hero_1536x1024_v1.webp`)}<h2>Cocoa Celebration Cake</h2><p>8 servings · mapping review only</p></div><div class="mapping-list">${[['Cake flour','300 g','1 kg','700 g','stoneground-cake-flour'],['Caster sugar','240 g','1 kg','760 g','fine-caster-sugar'],['Baking cocoa powder','180 g','250 g','70 g','baking-cocoa'],['Baking powder','8 g','100 g','92 g','baking-powder']].map((m,i)=>{const p=products.find(x=>x.id===m[4]);return `<article><span class="axis">0${i+1}</span>${art(p.material,`${p.title}, portfolio-demo packaging thumbnail.`,'',productSrc(p))}<div><h3>${m[0]}</h3><p>Required <strong>${m[1]}</strong> → selected <strong>${m[2]}</strong></p><small>Purchased ${m[2]} · leftover ${m[3]}</small></div><label><input type="checkbox" checked> Add ${p.sku}</label></article>`}).join('')}<div class="mapping-total"><p>4 of 4 available mappings selected</p><button>Add selected packs to demo cart</button></div></div></section>`,
  states:()=>`<section class="intro compact"><p class="kicker">Resilience contract</p><h1>Facts survive visual failure.</h1></section><div class="state-grid"><article><div class="asset failed" role="img" aria-label="Image unavailable"><span>Image unavailable</span></div><h2>Baking Cocoa Powder</h2><p>500 g · ML-BCP-500 · ₹315</p><p>Ingredients, allergens and storage: Information not provided.</p></article><article class="skeleton" aria-label="Loading product"><i></i><b></b><b></b><b></b><span>Loading product facts…</span></article><article><div class="notice"><strong>That pack is unavailable</strong><p>Your 500 g selection was kept. Choose another pack; nothing was added automatically.</p><button>Review pack sizes</button></div></article><article><div class="notice error"><strong>Images could not be loaded</strong><p>Product names, packs, prices and controls remain available.</p><button>Try images again</button></div></article></div>`,
  stress:()=>`<section class="intro compact"><p class="kicker">Content-fit and narrow-density test</p><h1>Long facts must wrap, not vanish.</h1></section><div class="stress-grid"><article>${art('box','Window cake box, shown as original portfolio-demo packaging.','',`${E}asset_pf5b_prod_window-cake-box_primary_1200_v1.webp`)}<p class="kicker">Packplane · Boxes</p><h2>Extra-Tall Windowed Celebration Cake Transport Box with Reinforced Interlocking Base</h2><p class="measure">30.5 × 30.5 × 35.6 cm · pack of 10</p><p>Compatibility and food-contact information not provided. Confirm dimensions against the finished bake, board and decorative height before selection.</p><strong>₹1,275.00</strong><small>PF-BOX-121214-XT · fictional demo</small></article><article><h2>Critical facts</h2><dl><dt>Material</dt><dd>Information not provided</dd><dt>Internal dimensions</dt><dd>30.5 × 30.5 × 35.6 cm</dd><dt>Assembly form</dt><dd>Flat-packed interlocking structure with separate reinforced base; description is illustrative demo content.</dd><dt>Compatibility</dt><dd>Information not provided</dd><dt>Food-contact information</dt><dd>Information not provided</dd></dl><button>Add to demo cart</button></article></div>`
};
document.querySelector('#main').innerHTML=(views[view]||views.contact)();
document.querySelectorAll('nav a').forEach(a=>a.toggleAttribute('aria-current',new URL(a.href).searchParams.get('view')===view));
document.querySelector('.nav-toggle').addEventListener('click',e=>{const open=e.currentTarget.getAttribute('aria-expanded')==='true';e.currentTarget.setAttribute('aria-expanded',String(!open));document.querySelector('#review-nav').classList.toggle('open',!open)});
const filter=()=>{const term=(document.querySelector('#search')?.value||'').trim().toLowerCase(),dept=document.querySelector('#dept')?.value||'';let n=0;document.querySelectorAll('#product-grid .product-card').forEach(el=>{const show=(!term||el.dataset.title.includes(term)||el.textContent.toLowerCase().includes(term))&&(!dept||el.dataset.dept===dept);el.hidden=!show;if(show)n++});if(document.querySelector('#result-count'))document.querySelector('#result-count').textContent=`${n} result${n===1?'':'s'}`;if(document.querySelector('#empty'))document.querySelector('#empty').hidden=n!==0};
document.querySelector('#search')?.addEventListener('input',filter);document.querySelector('#dept')?.addEventListener('change',filter);
document.querySelectorAll('.variant').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.variant').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');document.querySelector('#selection').textContent=`${b.textContent} selected · ${b.dataset.price} · ${b.dataset.sku}`}));
